version: '3.8'

services:

  frontend:
    build: ./frontend
    ports:
      - 8001:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 8002:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery worker -A  worker.app_worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend:/usr/src/backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  
  redis:
    image: redis:6-alpine
  
  dashboard:
    build: ./backend
    command:  celery flower -A worker.app_worker --loglevel=info
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
